# Generated by Django 5.1.3 on 2024-11-08 20:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DumDumUser',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NONE', 'Prefer not to disclose')], default='NONE', max_length=32)),
                ('wallet_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pijja',
            fields=[
                ('pijja_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('CREATED', 'Created'), ('PURCHASED', 'Purchased'), ('LOGGED', 'Logged')], default='CREATED', max_length=20)),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customapp.dumdumuser')),
            ],
        ),
    ]
