# Generated by Django 5.1.3 on 2024-11-08 22:12

import customapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pijja',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dumdumuser',
            name='user_id',
            field=models.CharField(default=customapp.models.generate_user_id, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dumdumuser',
            name='wallet_amount',
            field=models.FloatField(default=customapp.models.generate_wallet_amount),
        ),
        migrations.AlterField(
            model_name='pijja',
            name='pijja_id',
            field=models.CharField(default=customapp.models.generate_pizza_id, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pijja',
            name='price',
            field=models.FloatField(default=customapp.models.generate_random_pizza_price),
        ),
    ]
