# Generated by Django 5.1.3 on 2024-11-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0002_pijja_last_modified_at_alter_dumdumuser_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pijja',
            name='last_modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
