# Generated by Django 5.1.3 on 2024-11-09 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0003_alter_pijja_last_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pijja',
            name='last_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
