# Generated by Django 5.1.3 on 2024-11-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0005_alter_pijja_purchased_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pijja',
            name='purchased_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customapp.dumdumuser'),
        ),
    ]
