# Generated by Django 5.1.3 on 2024-11-09 16:14

import customapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0006_alter_pijja_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pijja',
            name='name',
            field=models.CharField(default=customapp.models.pick_random_pizza_name, max_length=192),
        ),
    ]
