pizza_names = [
    "Margherita Magnifica",
    "Pepperoni Paradise",
    "Veggie Volcano",
    "Meat Mania",
    "Hawaiian Heatwave",
    "BBQ Bonanza",
    "Buffalo Blitz",
    "Chicken Chaser",
    "Supreme Sizzler",
    "Four Cheese Fiesta",
    "Garden Galaxy",
    "Mushroom Medley",
    "Olive Oasis",
    "Artichoke Adventure",
    "Spinach Supreme",
    "Garlic Goodness",
    "Onion Odyssey",
    "Tomato Tango",
    "Pesto Perfection",
    "Ranch Rhapsody",
    "Spicy Fiesta",
    "Sweet Heat Sensation",
    "Caribbean Craze",
    "Mediterranean Marvel",
    "Greek Goddess",
    "Roman Empire",
    "Tuscan Treasure",
    "Sicilian Surprise",
    "Venetian Volcano",
    "Neapolitan Nightmare",
    "Detroit Dynamo",
    "Chicago Classic",
    "New York Nibbler",
    "California Dreamin'",
    "Texan Tornado",
    "Bayou Blast",
    "Rocky Mountain High",
    "Pacific Paradise",
    "Atlantic All-Star",
    "Gulf Coast Gourmet",
    "Big Cheese Bonanza",
    "Meat Lovers' Dream",
    "Veggie Vortex",
    "Vegan Venture",
    "Gluten-Free Gladiator",
    "Carnivore Carnival",
    "Herbivore Haven",
    "Omnivore's Delight",
    "The Big Kahuna",
    "Fiery Fiesta",
    "Tropical Temptation",
    "Forest Feast",
    "Ocean's Bounty",
    "Prairie Pickings",
    "Desert Delight",
    "Mountain Majesty",
    "River Run",
    "Jungle Jamboree",
    "Arctic Appetite",
    "Cosmic Craving",
    "Lunar Legend",
    "Solar Sizzle",
    "Galactic Grub",
    "Nebula Nibbler",
    "Comet Cuisine",
    "Asteroid Appetizer",
    "Supernova Special",
    "Black Hole Banquet",
    "Milky Way Munchies",
    "Big Dipper Dinner",
    "Orion's Feast",
    "Polaris Pizza",
    "Andromeda All-Stars",
    "Constellation Combo",
    "Quasar Quesadilla Pizza",
    "Pulsar Pie",
    "Zenith Zest",
    "Nadir Nosh",
    "Equinox Extravaganza",
    "Solstice Supper",
    "Aurora Australis",
    "Aurora Borealis",
    "Midnight Munchies",
    "Sunrise Surprise",
    "Sunset Special",
    "Twilight Temptation",
    "Dawn Delight",
    "Dusk Delicacy",
    "Northern Lights",
    "Southern Charm",
    "Eastern Elegance",
    "Western Wonder",
    "Golden Gourmet",
    "Silver Slicer",
    "Bronze Bomber",
    "Emerald Empire",
    "Ruby Royale",
    "Sapphire Sensation",
    "Diamond Delight",
    "Pearl Perfection",
    "Topaz Temptation",
    "Amethyst Allure",
    "Garnet Galore",
    "Opal Oasis",
    "Jade Jewel",
]